-- This file has been generated by Ion. Do not edit.
return {
    ["nmaild"] = {
        ["read"] = {
            [1] = "important",
            [2] = 40,
        },
        ["allnew"] = {
            [1] = "critical",
            [2] = 15,
        },
        ["check"] = {
            [1] = "~/mail/default",
        },
        ["allread"] = {
            [1] = "important",
            [2] = 30,
        },
        ["new"] = {
            [1] = "critical",
            [2] = 1,
        },
        ["update_interval"] = 5000,
    },
    ["stock"] = {
        ["unit"] = {
            ["delta"] = "%",
        },
        ["important"] = {
            ["delta"] = 0,
        },
        ["critical"] = {
            ["delta"] = 0,
        },
        ["susp_msg"] = "(Stock suspended)",
        ["interval"] = 300000,
        ["off_msg"] = "*Stock*",
        ["tickets"] = {
            [1] = "600036.ss",
            [2] = "000968.sz",
        },
        ["susp_msg_hint"] = "critical",
    },
    ["date"] = {
        ["date_format"] = "%H:%M %b.%d %a",
    },
    ["mail"] = {
    },
    ["load"] = {
    },
    ["weathercn"] = {
        ["city"] = "57036",
        ["hour"] = "48",
    },
}

