-- This file has been generated by Ion. Do not edit.
return {
    [0] = {
        ["type"] = "WRootWin",
        ["name"] = "WRootWin",
        ["managed"] = {
            [1] = {
                ["type"] = "WGroupWS",
                ["name"] = "WGroupWS",
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1024,
                    ["h"] = 768,
                },
                ["switchto"] = true,
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1024,
                            ["h"] = 768,
                        },
                        ["split_tree"] = {
                            ["tls"] = 17,
                            ["tl"] = {
                                ["type"] = "WSplitST",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 751,
                            ["br"] = {
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame<3>",
                                    ["managed"] = {
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [2] = {
                ["type"] = "WGroupWS",
                ["name"] = "WGroupWS<1>",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1024,
                    ["h"] = 768,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<1>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1024,
                            ["h"] = 768,
                        },
                        ["split_tree"] = {
                            ["tls"] = 17,
                            ["tl"] = {
                                ["type"] = "WSplitST",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 751,
                            ["br"] = {
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame<2>",
                                    ["managed"] = {
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [3] = {
                ["level"] = 1,
                ["type"] = "WGroupWS",
                ["name"] = "*scratchws*",
                ["pseudomodal"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1024,
                    ["h"] = 768,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["geom"] = {
                            ["y"] = 475,
                            ["x"] = 0,
                            ["w"] = 1024,
                            ["h"] = 293,
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*",
                        ["bottom"] = true,
                        ["level"] = 1025,
                        ["mode"] = 0,
                        ["managed"] = {
                            [1] = {
                                ["type"] = "WGroupCW",
                                ["name"] = "WGroupCW<4>",
                                ["geom"] = {
                                    ["y"] = 19,
                                    ["x"] = 0,
                                    ["w"] = 1024,
                                    ["h"] = 274,
                                },
                                ["switchto"] = true,
                                ["sizepolicy"] = "full",
                                ["managed"] = {
                                    [1] = {
                                        ["type"] = "WClientWin",
                                        ["bottom"] = true,
                                        ["windowid"] = 27262982,
                                        ["checkcode"] = 1,
                                        ["sizepolicy"] = "full",
                                        ["geom"] = {
                                            ["y"] = 0,
                                            ["x"] = 0,
                                            ["w"] = 1024,
                                            ["h"] = 274,
                                        },
                                        ["level"] = 1,
                                    },
                                },
                                ["level"] = 0,
                            },
                        },
                        ["sizepolicy"] = "free_glue_south",
                    },
                },
                ["unnumbered"] = true,
            },
        },
    },
}

